# ===== LOCAL =====
#spring.datasource.url=jdbc:mysql://localhost:3306/caderninho_db
#spring.datasource.username=root
#spring.datasource.password=123456

# ===== RAILWAY (RENDER) =====
#spring.datasource.url=jdbc:mysql://centerbeam.proxy.rlwy.net:22236/railway?useSSL=true&requireSSL=true&#allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=ZBezftEkhhBSvjljJFtQHiuQDIccTkXU
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#server.port=8080

spring.datasource.url=jdbc:mysql://centerbeam.proxy.rlwy.net:22236/caderninho?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=ZBezftEkhhBSvjljJFtQHiuQDIccTkXU
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080