services:
  - type: web
    name: e-caderninho
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 21